import {
  type LucideIcon,
  ArrowRight,
  Award,
  BarChart3,
  Bot,
  Building2,
  Calendar,
  Check,
  ChevronDown,
  CircleDot,
  Compass,
  Database,
  ExternalLink,
  GitBranch,
  Github,
  GraduationCap,
  Layers,
  Linkedin,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Phone,
  Rocket,
  Scan,
  Search,
  Settings,
  Shield,
  Sparkles,
  Target,
  Timer,
  TrendingUp,
  Users,
  Workflow,
  Wrench,
  X,
  Zap,
} from 'lucide-react'

/**
 * Icon-Namen wie in YAML (kebab-case oder kurze Namen) → Lucide-Komponente.
 * Erweitern, sobald neue Slides weitere Icons referenzieren.
 */
export const iconMap: Record<string, LucideIcon> = {
  'building-2': Building2,
  layers: Layers,
  bot: Bot,
  timer: Timer,
  'graduation-cap': GraduationCap,
  zap: Zap,
  rocket: Rocket,
  'arrow-right': ArrowRight,
  check: Check,
  'chevron-down': ChevronDown,
  menu: Menu,
  x: X,
  'external-link': ExternalLink,
  mail: Mail,
  phone: Phone,
  'map-pin': MapPin,
  linkedin: Linkedin,
  github: Github,
  calendar: Calendar,
  search: Search,
  wrench: Wrench,
  'message-circle': MessageCircle,
  target: Target,
  settings: Settings,
  users: Users,
  'trending-up': TrendingUp,
  compass: Compass,
  'bar-chart-3': BarChart3,
  'git-branch': GitBranch,
  workflow: Workflow,
  database: Database,
  sparkles: Sparkles,
  scan: Scan,
  shield: Shield,
  award: Award,
  'circle-dot': CircleDot,
}

export function getIcon(name: string): LucideIcon | null {
  return iconMap[name] ?? null
}
